import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT=path.dirname(fileURLToPath(import.meta.url));
const articles=JSON.parse(fs.readFileSync(path.join(ROOT,'content.json'),'utf8'));
const BASE='https://tawazon-health.vercel.app';
const PUBLISHER='ca-pub-1304668609520202';
const CATEGORIES={
 nutrition:{name:'التغذية',icon:'🥗',desc:'الغذاء المتوازن، المكونات والملصقات'},
 weight:{name:'الوزن والحميات',icon:'⚖️',desc:'نزول وزن واقعي وفهم الحميات الشائعة'},
 movement:{name:'الحركة',icon:'🏃',desc:'المشي والقوة وتقليل الخمول'},
 sleep:{name:'النوم',icon:'🌙',desc:'روتين النوم والطاقة والإيقاع اليومي'},
 digestion:{name:'الهضم',icon:'🌿',desc:'الألياف والإمساك وصحة الأمعاء'},
 supplements:{name:'المكملات',icon:'💊',desc:'الاستخدام الآمن للفيتامينات والمكملات'}
};
for(const legacy of ['articles','topics'])if(fs.existsSync(path.join(ROOT,legacy)))fs.rmSync(path.join(ROOT,legacy),{recursive:true,force:true});

const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ads=`<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${PUBLISHER}" crossorigin="anonymous"></script>`;
function shell(title,description,body,canonical,schema=''){
return `<!doctype html>
<html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${canonical}">
<meta property="og:type" content="website"><meta property="og:locale" content="ar_AR"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${BASE}/social-card.svg"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#0b1612">
<link rel="icon" href="/logo.svg"><link rel="alternate" type="application/rss+xml" title="مقالات توازن" href="/feed.xml"><link rel="stylesheet" href="/style.css">${ads}${schema}</head><body><div class="noise" aria-hidden="true"></div>
<header class="topbar"><a class="brand" href="/"><span class="brand-mark">ت</span><span>توازن<em>+</em></span></a><button class="menu" aria-label="فتح القائمة" aria-expanded="false">☰</button><nav><a href="/library.html">المكتبة</a><a href="/#paths">المسارات</a><a href="/editorial.html">منهجنا</a><a class="nav-pill" href="/about.html">عن توازن</a></nav></header>
<main>${body}</main><footer><div><a class="brand foot" href="/"><span class="brand-mark">ت</span><span>توازن<em>+</em></span></a><p>محتوى صحي عربي هادئ، موثّق، وقابل للتطبيق.</p></div><div class="footer-links"><a href="/about.html">عن الموقع</a><a href="/editorial.html">السياسة التحريرية</a><a href="/privacy.html">الخصوصية</a><a href="/disclaimer.html">إخلاء المسؤولية</a></div><p class="copyright">© 2026 توازن. المعلومات للتثقيف ولا تستبدل الرعاية الطبية.</p></footer><script src="/app.js" defer></script></body></html>`}

const card=a=>`<a class="article-card ${a.accent} reveal" data-category="${a.category}" data-search="${esc(a.title+' '+a.description+' '+a.kicker)}" href="/article-${a.slug}.html"><span class="card-icon">${a.icon}</span><div class="eyebrow">${a.kicker} · ${a.read}</div><h3>${a.title}</h3><p>${a.description}</p><span class="read-more">اقرأ الدليل <b>←</b></span></a>`;
const cards=articles.slice(0,12).map(card).join('');
let home=`<section class="hero"><div class="orb orb-one"></div><div class="orb orb-two"></div><div class="hero-copy reveal"><div class="status"><i></i> معرفة صحية بلا تهويل</div><h1>صحتك ليست<br><span>تحدياً مؤقتاً.</span></h1><p>مقالات عربية واضحة تساعدك على فهم التغذية والحركة والنوم، لتبني عادات تناسب حياتك لا موجة عابرة.</p><div class="hero-actions"><a class="primary" href="#latest">ابدأ القراءة <b>↓</b></a><a class="ghost" href="/library.html">استكشف المكتبة</a></div></div><div class="visual reveal"><div class="orbit o1"></div><div class="orbit o2"></div><div class="plate"><span>🥬</span><span>🥑</span><span>🫐</span><span>🍋</span><b>توازن</b></div><div class="metric m1"><strong>${articles.length}</strong><small>دليلاً<br>موثقاً</small></div><div class="metric m2"><strong>6</strong><small>مسارات<br>صحية</small></div></div></section><section class="trust-strip"><span>مصادر موثوقة</span><b>WHO</b><b>NIH</b><b>CDC</b><span>تحديث ومراجعة دورية</span></section><section class="section" id="latest"><div class="section-head reveal"><div><span class="section-no">01 / الأحدث</span><h2>اقرأ ما يفيدك<br>هذا الأسبوع</h2></div><p>نبدأ من السؤال الحقيقي، نفصل الدليل عن الادعاء، ونحوّل المعلومة إلى خطوة صغيرة قابلة للتطبيق.</p></div><div class="articles-grid">${cards}</div><div class="center-action"><a class="primary" href="/library.html">عرض المقالات كلها ←</a></div></section><section class="path-section" id="paths"><div class="section-head reveal"><div><span class="section-no">02 / اختر مسارك</span><h2>خطة صغيرة.<br>أثر يتراكم.</h2></div></div><div class="paths">${Object.entries(CATEGORIES).map(([slug,c],i)=>`<a href="/topic-${slug}.html"><span>0${i+1}</span><div><b>${c.icon} ${c.name}</b><small>${c.desc}</small></div><i>←</i></a>`).join('')}</div></section><section class="manifesto reveal"><span>مبدأ توازن</span><blockquote>أفضل خطة صحية هي التي تفهمها، تناسب حالتك، وتستطيع أن تعيش معها.</blockquote><a href="/editorial.html">تعرّف إلى منهجنا التحريري ←</a></section>`;
const webSchema=`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebSite',name:'توازن',url:BASE+'/',inLanguage:'ar',description:'محتوى صحي عربي موثوق عن التغذية والحركة والنوم.'})}</script>`;
fs.writeFileSync(path.join(ROOT,'index.html'),shell('توازن | صحة يومية بلا تعقيد','مقالات عربية موثوقة عن التغذية والكيتو وخسارة الوزن والحركة والنوم، بلغة واضحة وخطوات عملية.',home,BASE+'/',webSchema));

for(const a of articles){
 const toc=a.sections.map(([h],i)=>`<a href="#s${i+1}">${esc(h)}</a>`).join('');
 const sections=a.sections.map(([h,p],i)=>`<section id="s${i+1}"><span class="chapter">0${i+1}</span><h2>${esc(h)}</h2><p>${esc(p)}</p></section>`).join('');
 const sources=a.sources.map(([name,url])=>`<li><a href="${url}" rel="noopener noreferrer" target="_blank">${esc(name)} ↗</a></li>`).join('');
 const related=articles.filter(x=>x.slug!==a.slug&&x.category===a.category).slice(0,2).map(x=>`<a href="/article-${x.slug}.html"><span>${x.icon}</span><b>${x.title}</b></a>`).join('');
 const body=`<article class="article"><header class="article-hero ${a.accent}"><a class="back" href="/">الرئيسية / المقالات</a><div class="article-meta">${a.kicker} <i></i> ${a.read} <i></i> مراجعة: 21 سبتمبر 2026</div><h1>${a.title}</h1><p>${a.description}</p><div class="article-symbol">${a.icon}</div></header><div class="article-layout"><aside><b>في هذا الدليل</b>${toc}<div class="doctor-note">إذا كنت تستخدم دواءً أو لديك حالة مزمنة، راجع مختصاً قبل تغيير كبير.</div></aside><div class="article-content"><p class="lead">${a.intro}</p>${sections}<div class="sources"><h2>المصادر</h2><p>مصادر صحية رسمية استُخدمت للتحقق من المبادئ العامة:</p><ul>${sources}</ul></div></div></div></article><section class="more"><span>اقرأ أيضاً</span><div>${related}</div></section>`;
 const schema=`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.description,datePublished:'2026-09-21',dateModified:'2026-09-21',inLanguage:'ar',author:{'@type':'Organization',name:'فريق توازن'},publisher:{'@type':'Organization',name:'توازن'},mainEntityOfPage:`${BASE}/article-${a.slug}.html`})}</script>`;
 fs.writeFileSync(path.join(ROOT,`article-${a.slug}.html`),shell(`${a.title} | توازن`,a.description,body,`${BASE}/article-${a.slug}.html`,schema));
}

const filterButtons=`<button class="filter active" data-filter="all">الكل <b>${articles.length}</b></button>`+Object.entries(CATEGORIES).map(([slug,c])=>`<button class="filter" data-filter="${slug}">${c.icon} ${c.name} <b>${articles.filter(a=>a.category===slug).length}</b></button>`).join('');
const libraryBody=`<section class="library-hero"><span>مكتبة توازن</span><h1>إجابة واضحة<br>لسؤال صحي شائع.</h1><p>${articles.length} دليلاً عربياً في ستة مسارات، مع مصادر رسمية وتاريخ مراجعة واضح.</p><label class="search-box"><span>⌕</span><input id="article-search" type="search" placeholder="ابحث: الألياف، النوم، المشي..." autocomplete="off"></label></section><section class="library-wrap"><div class="filters" aria-label="تصفية المقالات">${filterButtons}</div><p id="results-count" class="results-count">عرض ${articles.length} مقالاً</p><div id="library-grid" class="articles-grid library-grid">${articles.map(card).join('')}</div><div id="empty-state" class="empty-state" hidden><b>لا توجد نتيجة مطابقة</b><p>جرّب كلمة أقصر أو اختر مساراً آخر.</p></div></section>`;
fs.writeFileSync(path.join(ROOT,'library.html'),shell(`المكتبة الصحية | توازن`,`مكتبة عربية تضم ${articles.length} دليلاً موثقاً عن التغذية والوزن والحركة والنوم والهضم والمكملات.`,libraryBody,`${BASE}/library.html`));
for(const [slug,c] of Object.entries(CATEGORIES)){
 const list=articles.filter(a=>a.category===slug);
 const body=`<section class="topic-hero"><span>${c.icon} مسار</span><h1>${c.name}</h1><p>${c.desc}. اقرأ الأدلة بترتيب يناسب سؤالك، وارجع إلى المصادر في نهاية كل مقال.</p><a class="ghost" href="/library.html">← جميع المسارات</a></section><section class="section"><div class="section-head"><div><span class="section-no">${list.length} أدلة</span><h2>في هذا المسار</h2></div></div><div class="articles-grid">${list.map(card).join('')}</div></section>`;
 fs.writeFileSync(path.join(ROOT,`topic-${slug}.html`),shell(`${c.name} | توازن`,c.desc,body,`${BASE}/topic-${slug}.html`));
}

const pages={
 'about.html':['عن توازن','منصة محتوى صحي عربي تضع الوضوح والمصادر والسياق قبل الوعود السريعة.',`<section class="page-hero"><span>عن توازن</span><h1>المعلومة الصحية<br>تستحق الهدوء.</h1><p>توازن موقع تثقيفي عربي يشرح موضوعات التغذية والحركة والنوم بلغة واضحة. لا نبيع حلولاً سحرية ولا نشخّص الحالات الطبية.</p></section><section class="prose"><h2>ما الذي نقدمه؟</h2><p>أدلة عملية تبدأ من المصادر الصحية الرسمية، وتوضح حدود المعلومة ومن يحتاج إلى استشارة مختص. نكتب للقارئ الذي يريد فهماً أفضل قبل اتخاذ قرار.</p><h2>من يكتب المحتوى؟</h2><p>يعد فريق التحرير المسودة ويقارن الادعاءات بالمصادر المذكورة في نهاية كل مقال. عند تناول إرشاد شخصي أو حالة مرضية، نوجّه القارئ إلى الطبيب أو اختصاصي التغذية المرخّص.</p><h2>تواصل</h2><p>سيضاف بريد التواصل الرسمي عند ربط النطاق.</p></section>`],
 'editorial.html':['السياسة التحريرية','كيف يختار توازن مصادره ويراجع محتواه الصحي ويصحح الأخطاء.',`<section class="page-hero"><span>السياسة التحريرية</span><h1>مصدر واضح.<br>ادعاء محسوب.</h1><p>نستخدم مصادر صحية رسمية وبحوثاً محكمة، ونميّز بين الإرشادات العامة والرعاية الفردية.</p></section><section class="prose"><h2>اختيار الموضوع</h2><p>نختار الأسئلة الشائعة التي يمكن شرحها بأمان، ونبتعد عن التشخيص والوصفات الدوائية الفردية. العناوين لا تعد بنتيجة مضمونة.</p><h2>المصادر والمراجعة</h2><p>تعتمد المقالات على جهات صحية رسمية مثل منظمة الصحة العالمية وNIDDK وCDC، وتعرض روابطها في نهاية المقال. نراجع المحتوى عند ظهور إرشادات جديدة، ونضع تاريخ المراجعة بوضوح.</p><h2>التصحيح</h2><p>إذا ظهر خطأ مؤثر، نصححه ونحدّث تاريخ المراجعة.</p><h2>الإعلانات والاستقلال</h2><p>قد يعرض الموقع إعلانات بواسطة Google AdSense بعد الموافقة. لا يغيّر المعلنون المحتوى، ولا نخلط الإعلان بالتوصية الصحية.</p></section>`],
 'privacy.html':['سياسة الخصوصية','سياسة الخصوصية وملفات الارتباط والإعلانات في موقع توازن.',`<section class="page-hero compact"><span>الخصوصية</span><h1>خصوصيتك تهمنا.</h1><p>آخر تحديث: 21 سبتمبر 2026</p></section><section class="prose"><h2>البيانات</h2><p>لا يطلب الموقع حالياً إنشاء حساب أو إدخال بيانات صحية. قد تسجل خدمات الاستضافة بيانات تقنية معتادة مثل عنوان IP ونوع المتصفح لأغراض الأمان والأداء.</p><h2>ملفات الارتباط والإعلانات</h2><p>قد تستخدم Google، بصفتها مورداً خارجياً، ملفات ارتباط لعرض الإعلانات وقياس أدائها بعد موافقة الموقع في AdSense. يمكن إدارة تخصيص الإعلانات من إعدادات إعلانات Google. سنعرض خيارات الموافقة المطلوبة للزوار في المناطق التي تفرض ذلك.</p><h2>الروابط الخارجية</h2><p>تؤدي بعض الروابط إلى مصادر صحية خارجية لها سياسات مستقلة. لا نشارك معلومات طبية شخصية مع هذه الجهات.</p></section>`],
 'disclaimer.html':['إخلاء المسؤولية الصحية','حدود استخدام المحتوى الصحي المنشور في توازن.',`<section class="page-hero compact"><span>إخلاء المسؤولية</span><h1>للتثقيف، لا للتشخيص.</h1><p>المحتوى العام لا يعرف تاريخك الطبي أو أدويتك أو نتائج فحوصك.</p></section><section class="prose"><h2>ليست نصيحة طبية شخصية</h2><p>المعلومات في توازن لأغراض التثقيف العام ولا تستبدل تشخيص الطبيب أو خطة اختصاصي تغذية مرخص. لا تؤخر طلب الرعاية بسبب مقال قرأته هنا.</p><h2>الحالات الطارئة</h2><p>عند ألم الصدر أو صعوبة التنفس أو الإغماء أو ارتباك مفاجئ أو علامات حالة طارئة، اتصل بخدمات الطوارئ المحلية فوراً.</p><h2>الحميات والأدوية</h2><p>قد تؤثر التغييرات الغذائية والصيام في سكر الدم والضغط وجرعات الدواء. الحوامل والمرضعات والأطفال ومن لديهم مرض مزمن أو اضطراب أكل يحتاجون إلى توجيه مهني قبل تغيير كبير.</p></section>`]
};
for(const [file,[title,desc,body]] of Object.entries(pages))fs.writeFileSync(path.join(ROOT,file),shell(`${title} | توازن`,desc,body,`${BASE}/${file}`));
fs.writeFileSync(path.join(ROOT,'ads.txt'),'google.com, pub-1304668609520202, DIRECT, f08c47fec0942fa0\n');
fs.writeFileSync(path.join(ROOT,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${BASE}/sitemap.xml\n`);
const urls=['/','/library.html','/about.html','/editorial.html','/privacy.html','/disclaimer.html',...Object.keys(CATEGORIES).map(c=>`/topic-${c}.html`),...articles.map(a=>`/article-${a.slug}.html`)];
fs.writeFileSync(path.join(ROOT,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(u=>`  <url><loc>${BASE}${u}</loc><lastmod>2026-09-21</lastmod></url>`).join('\n')+'\n</urlset>\n');
const rssItems=articles.map(a=>`<item><title>${esc(a.title)}</title><link>${BASE}/article-${a.slug}.html</link><guid>${BASE}/article-${a.slug}.html</guid><description>${esc(a.description)}</description><pubDate>Mon, 21 Sep 2026 08:00:00 GMT</pubDate></item>`).join('');
fs.writeFileSync(path.join(ROOT,'feed.xml'),`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>توازن</title><link>${BASE}/</link><description>مقالات عربية موثوقة عن التغذية والحركة والنوم.</description><language>ar</language>${rssItems}</channel></rss>`);
console.log(`Built ${urls.length} indexable pages in ${ROOT}`);
const output=path.join(ROOT,'dist');
fs.mkdirSync(output,{recursive:true});
for(const name of fs.readdirSync(ROOT)){
 if(/\.(html|css|js|svg|xml|txt)$/.test(name))fs.copyFileSync(path.join(ROOT,name),path.join(output,name));
}
